[ci] Self hosted sbt preflights and static checks (#15241)

diff --git a/.circleci/config/jobs/preflight_check.yml b/.circleci/config/jobs/preflight_check.yml
--- a/.circleci/config/jobs/preflight_check.yml
+++ b/.circleci/config/jobs/preflight_check.yml
@@ -1,4 +1,136 @@
 jobs:
+  preflight_check_docker:
+    parameters:
+      <<: *cluster-parameter
+      <<: *channel-notify-parameter
+      test_names_file:
+        type: string
+        default: "test-full-class-names-docker-compose-validator-preflight.log"
+      wait_for_sv:
+        type: boolean
+        default: true
+      wait_for_splitwell:
+        type: boolean
+        default: true
+      cluster_version:
+        type: string
+        default: ""
+      check_cluster_version:
+        type: boolean
+        default: true
+      migration_id:
+        type: integer
+        default: 0
+      extra_env_vars:
+        type: string
+        default: ""
+      force_non_devnet:
+        type: boolean
+        default: false
+    machine:
+      image: ubuntu-2204:2024.01.1
+    environment:
+      <<: *env
+      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
+      VPN_HOST_IP: 34.132.91.75
+    parallelism: 1
+    steps:
+      - checkout_with_retry
+      - run:
+          # necessary for npm/webpack dev server launched in start-frontends.sh later
+          # https://webpack.js.org/configuration/watch/#not-enough-watchers
+          name: Set inotify fs watch
+          command: |
+            echo "Checking watch info..."
+            sysctl fs.inotify
+            echo "Setting max_user_watches..."
+            echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
+      - when:
+          condition: << parameters.cluster_version >>
+          steps:
+            - run:
+                name: Checkout commit << parameters.cluster_version >>
+                command: git checkout << parameters.cluster_version >>
+      - setup_nix
+      - run_bash_command_in_nix:
+          cmd_name: Activate cluster (configure kubectl)
+          cluster: << parameters.cluster >>
+          gce_authenticate: true
+          cmd: cncluster activate
+          cmd_retry_count: 5
+      # TODO(#6630): bundle all these restores into a command, consider merging with setup_sbt_test_job
+      - restore_sbt_cache
+      - restore_precompiled_classes
+      - restore_frontend_node_modules
+      - restore_daml_artifacts
+      - split_tests_for_parallel_run:
+          test_names_file: << parameters.test_names_file >>
+      - setup_vpn
+      - setup_vpn_routes:
+          cluster: << parameters.cluster >>
+      - run_bash_command_in_nix:
+          cmd_name: wait for deployment to finish
+          cluster: << parameters.cluster >>
+          additional_nix_args: "--keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
+          cmd: |
+            if [[ << parameters.check_cluster_version >> == true ]]; then
+              VERSION=$(get-snapshot-version)
+              cncluster wait_version $VERSION
+            fi
+            validator_app="validator-app"
+            # We use readiness of validator-app in all namespaces as an approximation to the cluster's readiness
+            if [[ << parameters.wait_for_splitwell >> == true ]]; then
+              cncluster wait splitwell $validator_app << parameters.migration_id >>
+            fi
+            cncluster wait sv-1 $validator_app << parameters.migration_id >>
+            cncluster wait validator1 $validator_app << parameters.migration_id >>
+            if (env-bool IS_DEVNET) && [ << parameters.force_non_devnet >> == false ]; then
+              cncluster wait sv-2 $validator_app << parameters.migration_id >>
+              cncluster wait sv-3 $validator_app << parameters.migration_id >>
+              cncluster wait sv-4 $validator_app << parameters.migration_id >>
+            fi
+            if [[ << parameters.wait_for_sv >> == true ]] && ( env-bool APPROVE_SV_RUNBOOK || env-bool IS_DEVNET ); then
+              cncluster wait sv $validator_app << parameters.migration_id >>
+            fi
+            echo "Done waiting. All pods in the cluster are:"
+            kubectl get pods -A
+          cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
+          cmd_retry_count: 2
+          cmd_before_retry: |-
+            echo "VPN connection seems to have died, restarting VPN and retrying..."
+            /tmp/vpn-scripts/restart-vpn.sh
+      - get_cluster:
+          cluster: << parameters.cluster >>
+      - docker_login_internal
+      - run_bash_command_in_nix:
+          cmd: /tmp/vpn-scripts/create-docker-network-on-vpn.sh onvpn
+      - execute_sbt_command:
+          pre_sbt_cmd: |
+            set -eou pipefail
+            . cluster/deployment/${TARGET_CLUSTER}/.envrc.vars
+          cmd: "\"$RUN_SPLITTED_TESTS_CMD\""
+          additional_nix_args: "--keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET --keep SV_DEV_NET_WEB_UI_PASSWORD --keep SV_WEB_UI_PASSWORD --keep VALIDATOR_WEB_UI_PASSWORD --keep GCP_DATA_DUMP_BUCKET_SERVICE_ACCOUNT_CREDENTIALS --keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
+          extra_env_vars: POSTGRES_DB=postgres NETWORK_APPS_ADDRESS=${GCP_CLUSTER_HOSTNAME} NETWORK_APPS_ADDRESS_PROTOCOL=https VALIDATOR_USER_NAME="auto_preflight" MIGRATION_ID=<< parameters.migration_id >> << parameters.extra_env_vars >>
+          timeout: "15m"
+          cmd_retry_count: 3
+          # retry if VPN got disconnected (approximated by trying to fetch docs from the cluster.
+          # Note that this is expected to succeed even if the cluster deployment is down, because it fetches only the http->https redirect anyway)
+          cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
+          cluster: << parameters.cluster >>
+          cmd_before_retry: |
+            echo "Test failed, but VPN connection seems to have died, restarting VPN and retrying..."
+            ./stop-frontends.sh
+            /tmp/vpn-scripts/restart-vpn.sh
+      - print_gcloud_logs_commands:
+          cluster: <<parameters.cluster>>
+      - cleanup_sbt_test_job
+      - notify-cluster-fail:
+          cluster: << parameters.cluster >>
+          channel_notify: << parameters.channel_notify >>
+      - store_artifacts:
+          name: Upload vpn log
+          path: /var/log/vpn.log
+
   preflight_check:
     parameters:
       <<: *cluster-parameter
@@ -30,15 +162,9 @@ jobs:
       force_non_devnet:
         type: boolean
         default: false
-      with_docker:
-        type: boolean
-        default: false
-    machine:
-      image: ubuntu-2204:2024.01.1
+    executor: self_hosted
     environment:
       <<: *env
-      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
-      VPN_HOST_IP: 34.132.91.75
     parallelism: 1
     steps:
       - run:
@@ -66,27 +192,19 @@ jobs:
                   - run:
                       name: Checkout commit << parameters.cluster_version >>
                       command: git checkout << parameters.cluster_version >>
-            - setup_nix
+            - setup_nix_self_hosted
             - run_bash_command_in_nix:
                 cmd_name: Activate cluster (configure kubectl)
                 cluster: << parameters.cluster >>
                 gce_authenticate: true
                 cmd: cncluster activate
                 cmd_retry_count: 5
-            # TODO(#6630): bundle all these restores into a command, consider merging with setup_sbt_test_job
-            - restore_sbt_cache
-            - restore_precompiled_classes
-            - restore_frontend_node_modules
-            - restore_daml_artifacts
+            - restore_sbt_cache_self_hosted
             - split_tests_for_parallel_run:
                 test_names_file: << parameters.test_names_file >>
-            - setup_vpn
-            - setup_vpn_routes:
-                cluster: << parameters.cluster >>
             - run_bash_command_in_nix:
                 cmd_name: wait for deployment to finish
                 cluster: << parameters.cluster >>
-                additional_nix_args: "--keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
                 cmd: |
                   if [[ << parameters.check_cluster_version >> == true ]]; then
                     VERSION=$(get-snapshot-version)
@@ -109,46 +227,23 @@ jobs:
                   fi
                   echo "Done waiting. All pods in the cluster are:"
                   kubectl get pods -A
-                cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
-                cmd_retry_count: 2
-                cmd_before_retry: |-
-                  echo "VPN connection seems to have died, restarting VPN and retrying..."
-                  /tmp/vpn-scripts/restart-vpn.sh
             - get_cluster:
                 cluster: << parameters.cluster >>
-            - when:
-                condition: << parameters.with_docker >>
-                steps:
-                  - docker_login_internal
-                  - run_bash_command_in_nix:
-                      cmd: /tmp/vpn-scripts/create-docker-network-on-vpn.sh onvpn
             - execute_sbt_command:
+                cluster: << parameters.cluster >>
                 pre_sbt_cmd: |
                   set -eou pipefail
                   . cluster/deployment/${TARGET_CLUSTER}/.envrc.vars
                 cmd: "\"$RUN_SPLITTED_TESTS_CMD\""
-                additional_nix_args: "--keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET --keep SV_DEV_NET_WEB_UI_PASSWORD --keep SV_WEB_UI_PASSWORD --keep VALIDATOR_WEB_UI_PASSWORD --keep GCP_DATA_DUMP_BUCKET_SERVICE_ACCOUNT_CREDENTIALS --keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
+                additional_nix_args: "--keep AUTH0_CN_MANAGEMENT_API_CLIENT_ID --keep AUTH0_CN_MANAGEMENT_API_CLIENT_SECRET --keep SV_DEV_NET_WEB_UI_PASSWORD --keep SV_WEB_UI_PASSWORD --keep VALIDATOR_WEB_UI_PASSWORD --keep GCP_DATA_DUMP_BUCKET_SERVICE_ACCOUNT_CREDENTIALS"
                 extra_env_vars: POSTGRES_DB=postgres NETWORK_APPS_ADDRESS=${GCP_CLUSTER_HOSTNAME} NETWORK_APPS_ADDRESS_PROTOCOL=https VALIDATOR_USER_NAME="auto_preflight" MIGRATION_ID=<< parameters.migration_id >> << parameters.extra_env_vars >>
                 timeout: "15m"
-                cmd_retry_count: 3
-                # retry if VPN got disconnected (approximated by trying to fetch docs from the cluster.
-                # Note that this is expected to succeed even if the cluster deployment is down, because it fetches only the http->https redirect anyway)
-                cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
-                cluster: << parameters.cluster >>
-                cmd_before_retry: |
-                  echo "Test failed, but VPN connection seems to have died, restarting VPN and retrying..."
-                  ./stop-frontends.sh
-                  /tmp/vpn-scripts/restart-vpn.sh
-
             - print_gcloud_logs_commands:
                 cluster: <<parameters.cluster>>
-            - cleanup_sbt_test_job
+            - save_sbt_cache_self_hosted
             - notify-cluster-fail:
                 cluster: << parameters.cluster >>
                 channel_notify: << parameters.channel_notify >>
-            - store_artifacts:
-                name: Upload vpn log
-                path: /var/log/vpn.log
 
   preflight_sv_check:
     parameters:
@@ -172,12 +267,9 @@ jobs:
       force_non_devnet:
         type: boolean
         default: false
-    machine:
-      image: ubuntu-2204:2024.01.1
+    executor: self_hosted
     environment:
       <<: *env
-      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
-      VPN_HOST_IP: 34.132.91.75
     steps:
       - run:
           # CircleCI does not allow a job to only contain a when (because when false, there's no steps)
@@ -195,26 +287,14 @@ jobs:
                   - run:
                       name: Checkout commit << parameters.cluster_version >>
                       command: git checkout << parameters.cluster_version >>
-            - setup_nix
+            - setup_nix_self_hosted
             - run_bash_command_in_nix:
                 cmd_name: Activate cluster (configure kubectl)
                 cluster: << parameters.cluster >>
                 gce_authenticate: true
                 cmd: cncluster activate
                 cmd_retry_count: 5
-            - restore_sbt_cache
-            - restore_precompiled_classes
-            - restore_frontend_node_modules
-            - restore_daml_artifacts
-            # We run sbt update with retries first to ensure that all dependency artifacts have been downloaded
-            - execute_sbt_command:
-                cmd: "update"
-                cmd_retry_count: 3
-            - execute_sbt_command:
-                cmd: "Test/compile"
-            - setup_vpn
-            - setup_vpn_routes:
-                cluster: << parameters.cluster >>
+            - restore_sbt_cache_self_hosted
             - wait_for_sv_runbook_deployment:
                 cluster: << parameters.cluster >>
                 check_cluster_version: << parameters.check_cluster_version >>
@@ -239,8 +319,7 @@ jobs:
                   --keep ARTIFACTORY_USER \
                   --keep ARTIFACTORY_PASSWORD \
                   --keep AUTH0_SV_MANAGEMENT_API_CLIENT_ID \
-                  --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET \
-                  --keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
+                  --keep AUTH0_SV_MANAGEMENT_API_CLIENT_SECRET"
                 cluster: << parameters.cluster >>
                 cmd: |
                   export MIGRATION_ID=<< parameters.migration_id >>
@@ -250,23 +329,12 @@ jobs:
                     export PREAPPROVE_VALIDATOR_RUNBOOK=true
                   fi
                   cncluster preflight_sv
-                cmd_retry_count: 3
-                # retry if VPN got disconnected (approximated by trying to fetch docs from the cluster.
-                # Note that this is expected to succeed even if the cluster deployment is down, because it fetches only the http->https redirect anyway)
-                cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
-                cmd_before_retry: |
-                  echo "Test failed, but VPN connection seems to have died, restarting VPN and retrying..."
-                  ./stop-frontends.sh
-                  /tmp/vpn-scripts/restart-vpn.sh
             - print_gcloud_logs_commands:
                 cluster: <<parameters.cluster>>
-            - cleanup_sbt_test_job
+            - save_sbt_cache_self_hosted
             - notify-cluster-fail:
                 cluster: << parameters.cluster >>
                 channel_notify: << parameters.channel_notify >>
-            - store_artifacts:
-                name: Upload vpn log
-                path: /var/log/vpn.log
 
   preflight_validator_check:
     parameters:
@@ -290,12 +358,9 @@ jobs:
       force_non_devnet:
         type: boolean
         default: false
-    machine:
-      image: ubuntu-2204:2024.01.1
+    executor: self_hosted
     environment:
       <<: *env
-      VPN_HOST_NAME: vpn-cn-devnet.da-int.net
-      VPN_HOST_IP: 34.132.91.75
     steps:
       - run:
         # CircleCI does not allow a job to only contain a when (because when false, there's no steps)
@@ -313,30 +378,19 @@ jobs:
                   - run:
                       name: Checkout commit << parameters.cluster_version >>
                       command: git checkout << parameters.cluster_version >>
-            - setup_nix
+            - setup_nix_self_hosted
             - run_bash_command_in_nix:
                 cmd_name: Activate cluster (configure kubectl)
                 cluster: << parameters.cluster >>
                 gce_authenticate: true
                 cmd: cncluster activate
                 cmd_retry_count: 5
-            - restore_sbt_cache
-            - restore_precompiled_classes
-            - restore_frontend_node_modules
-            - restore_daml_artifacts
-            # We run sbt update with retries first to ensure that all dependency artifacts have been downloaded
-            - execute_sbt_command:
-                cmd: "update"
-                cmd_retry_count: 3
+            - restore_sbt_cache_self_hosted
             - execute_sbt_command:
                 cmd: "Test/compile"
-            - setup_vpn
-            - setup_vpn_routes:
-                cluster: << parameters.cluster >>
             - run_bash_command_in_nix:
                 cmd_name: wait for validator-runbook deployment to finish
                 cluster: << parameters.cluster >>
-                additional_nix_args: "--keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
                 cmd: |
                   if [[ << parameters.check_cluster_version >> == true ]]; then
                     VERSION=$(get-snapshot-version)
@@ -346,11 +400,6 @@ jobs:
                   cncluster wait validator validator-app << parameters.migration_id >>
                   echo "Done waiting. All pods in the cluster are:"
                   kubectl get pods -A
-                cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
-                cmd_retry_count: 2
-                cmd_before_retry: |-
-                  echo "VPN connection seems to have died, restarting VPN and retrying..."
-                  /tmp/vpn-scripts/restart-vpn.sh
             # TODO(#8300): remove this dependency and check once canton handles sequencer connections more gracefully
             - wait_for_sv_runbook_deployment:
                 cluster: << parameters.cluster >>
@@ -375,8 +424,7 @@ jobs:
                   --keep ARTIFACTORY_USER \
                   --keep ARTIFACTORY_PASSWORD \
                   --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_ID \
-                  --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET \
-                  --keep VPN_HOST_NAME --keep VPN_USER --keep VPN_PASSWORD --keep VPN_HOST_IP"
+                  --keep AUTH0_VALIDATOR_MANAGEMENT_API_CLIENT_SECRET"
                 cluster: << parameters.cluster >>
                 cmd: |
                   export MIGRATION_ID=<< parameters.migration_id >>
@@ -386,20 +434,9 @@ jobs:
                     export PREAPPROVE_VALIDATOR_RUNBOOK=true
                   fi
                   cncluster preflight_validator
-                cmd_retry_count: 3
-                # retry if VPN got disconnected (approximated by trying to fetch docs from the cluster.
-                # Note that this is expected to succeed even if the cluster deployment is down, because it fetches only the http->https redirect anyway)
-                cmd_retry_condition: $(if curl --connect-timeout 5 -s ${GCP_CLUSTER_HOSTNAME}; then echo "false"; else echo "true"; fi)
-                cmd_before_retry: |
-                  echo "Test failed, but VPN connection seems to have died, restarting VPN and retrying..."
-                  ./stop-frontends.sh
-                  /tmp/vpn-scripts/restart-vpn.sh
             - print_gcloud_logs_commands:
                 cluster: <<parameters.cluster>>
-            - cleanup_sbt_test_job
+            - save_sbt_cache_self_hosted
             - notify-cluster-fail:
                 cluster: << parameters.cluster >>
                 channel_notify: << parameters.channel_notify >>
-            - store_artifacts:
-                name: Upload vpn log
-                path: /var/log/vpn.log
