list_sv_cometbft_addresses no longer depends on pulumi (#12801)

diff --git a/build-tools/cncluster b/build-tools/cncluster
--- a/build-tools/cncluster
+++ b/build-tools/cncluster
@@ -2722,12 +2722,37 @@ function subcmd_preflight_sv_reonboard() {
 subcommand_whitelist[list_sv_cometbft_addresses]='List the sv cometbft addresses'
 
 function subcmd_list_sv_cometbft_addresses() {
-  sv=$1
-  token=$(subcmd_get_token "${sv}")
+  sv="${1-}"
+  domain=${2:-0}
+
+  if [ -z "${sv}" ]; then
+    _error "Usage: $SCRIPTNAME list_sv_cometbft_addresses <sv-name> [domain_migration_id]"
+  fi
+
+  cleanup() {
+    kill $port_forward_pid
+  }
+  trap cleanup EXIT
+  kubectl port-forward -n "$sv" deployment/global-domain-"$domain"-cometbft 26657:26657 > /dev/null &
+  port_forward_pid=$!
+
+  if ! kill -0 $port_forward_pid; then
+    _error "Failed to start port forwarding"
+    exit 1
+  fi
+
+  while ! nc -z -w 1 localhost 26657 > /dev/null 2>&1; do
+    sleep 0.1
+    if [ $SECONDS -ge 10 ]; then
+      echo "Failed to port-forward to $sv cometbft pod"
+      cleanup
+      exit 1
+    fi
+  done
   pubkey_sv=$(mktemp)
   pubkey_address=$(mktemp)
   curl -sSLf "https://sv.$sv.${GCP_CLUSTER_HOSTNAME}/api/sv/v0/dso" | jq '[.sv_node_states[] | .payload as $payload | .payload.state.synchronizerNodes[] | select(.[0] | startswith("global"))[1].cometBft.nodes[]|{ sv: $payload.svName, pub_key: .[1].validatorPubKey}]' > "$pubkey_sv"
-  curl -sSLf "https://sv.$sv.${GCP_CLUSTER_HOSTNAME}/api/sv/v0/admin/domain/cometbft/debug" -H "Authorization: Bearer $token" -H "Content-Type: application/json" | jq '[.validators.validators[] | { address: .address, pub_key:  .pub_key.value}] | to_entries | map({index: .key, pub_key: .value.pub_key, address: .value.address})' > "$pubkey_address"
+  curl -sSLf --header "Content-Type: application/json" 'localhost:26657/validators' | jq '[.result.validators[] | { address: .address, pub_key:  .pub_key.value}] | to_entries | map({index: .key, pub_key: .value.pub_key, address: .value.address})' > "$pubkey_address"
 
   jq -s '[ .[0] + .[1] | group_by(.pub_key)[] | select(length > 1) | add ] | sort_by(.index)' "$pubkey_address" "$pubkey_sv"
 }
