add retries
Signed-off-by: Itai Segall <itai.segall@digitalasset.com>

diff --git a/build-tools/docker-scan b/build-tools/docker-scan
--- a/build-tools/docker-scan
+++ b/build-tools/docker-scan
@@ -17,18 +17,33 @@ TMP_DIR="/tmp/blackduck-docker-scan/${index}"
 mkdir -p "${TMP_DIR}"
 export DETECT_JAR_DOWNLOAD_DIR="${TMP_DIR}/detect_jars"
 
-bash <(curl -s https://detect.blackduck.com/detect10.sh) \
-  --blackduck.url=https://digitalasset.blackducksoftware.com/ \
-  --blackduck.api.token="$BLACKDUCK_HUBDETECT_TOKEN" \
-  --detect.docker.image="$image" \
-  --detect.tools=DOCKER,SIGNATURE_SCAN \
-  --detect.tools.excluded=BINARY_SCAN \
-  --detect.project.name=DACH-NY_canton-network-internal_images \
-  --detect.project.version.name="$image" \
-  --detect.docker.passthrough.imageinspector.service.port.alpine=$((BASE_PORT + (index*3) + 0)) \
-  --detect.docker.passthrough.imageinspector.service.port.centos=$((BASE_PORT + (index*3) + 1)) \
-  --detect.docker.passthrough.imageinspector.service.port.ubuntu=$((BASE_PORT + (index*3) + 2)) \
-  --detect.output.path="${TMP_DIR}/output" \
-  --detect.tools.output.path="${TMP_DIR}/tool_output" \
+for i in {1..10}; do
+  set +e
+  bash <(curl -s https://detect.blackduck.com/detect10.sh) \
+    --blackduck.url=https://digitalasset.blackducksoftware.com/ \
+    --blackduck.api.token="$BLACKDUCK_HUBDETECT_TOKEN" \
+    --detect.docker.image="$image" \
+    --detect.tools=DOCKER,SIGNATURE_SCAN \
+    --detect.tools.excluded=BINARY_SCAN \
+    --detect.project.name=DACH-NY_canton-network-internal_images \
+    --detect.project.version.name="$image" \
+    --detect.docker.passthrough.imageinspector.service.port.alpine=$((BASE_PORT + (index*3) + 0)) \
+    --detect.docker.passthrough.imageinspector.service.port.centos=$((BASE_PORT + (index*3) + 1)) \
+    --detect.docker.passthrough.imageinspector.service.port.ubuntu=$((BASE_PORT + (index*3) + 2)) \
+    --detect.output.path="${TMP_DIR}/output" \
+    --detect.tools.output.path="${TMP_DIR}/tool_output"
+  res=$?
+  set -e
+
+  if [ $res -eq 0 ]; then
+    echo "Black Duck scan completed successfully for image: $image"
+    exit 0
+  else
+    echo "Black Duck scan failed (attempt $i), retrying in 10 seconds..."
+    sleep 10
+  fi
+done
+echo "Black Duck scan failed after 10 attempts for image: $image"
+exit 1
 
 #TODO(DACH-NY/canton-network-internal#726): run also with `--detect.docker.platform.top.layer.id=sha256:...`, to detect separately vulnerabilities added by us on top of the base image
