done, test me
Signed-off-by: Itai Segall <itai.segall@digitalasset.com>

diff --git a/build-tools/docker-scan b/build-tools/docker-scan
--- a/build-tools/docker-scan
+++ b/build-tools/docker-scan
@@ -6,11 +6,14 @@ script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
 source "${script_dir}/lib/libcli.source"
 
 image="$(<target/image-tag)"
+image_name="$(basename "$(pwd)")"
+image_version="$(get-snapshot-version)"
+
 
 # Compute a unique index per image name, to be used for tmp directories and port numbers,
 # as otherwise blackduck is unhappy with parallelism
 # shellcheck disable=SC2012,SC2010
-index=$(ls .. | grep -nx "$(basename "$(pwd)")" | sed 's/:.*//')
+index=$(ls .. | grep -nx "${image_name}" | sed 's/:.*//')
 
 BASE_PORT=9000
 TMP_DIR="/tmp/blackduck-docker-scan/${index}"
@@ -32,36 +35,36 @@ EOF
 
   echo "Base image: $base_image"
 
-  if docker buildx imagetools inspect ${base_image} --raw | jq -r '.manifests[]' &> /dev/null; then
-    echo "Base image is a multi-arch image."
-    base_image_digest=$(docker buildx imagetools inspect ${base_image} --raw | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')
+  if docker buildx imagetools inspect "${base_image}" --raw | jq -r '.manifests[]' &> /dev/null; then
+    # Base image is a multi-arch image
+    # base_image_digest=$(docker buildx imagetools inspect "${base_image}" --raw | jq -r '.manifests[] | select(.platform.architecture == "amd64") | .digest')
+    # layers=$(docker buildx imagetools inspect "${base_image}" --format '{{json .}}' | jq '.image."linux/amd64".rootfs.diff_ids')
+    last_layer=$(docker buildx imagetools inspect "${base_image}" --format '{{json .}}' | jq -r '.image."linux/amd64".rootfs.diff_ids[-1]')
   else
-    echo "Base image is not a multi-arch image, using the default architecture."
-    base_image_digest=$(docker buildx imagetools inspect ${base_image} --raw | jq -r '.digest')
+    # Base image is not a multi-arch image, using the default architecture
+    # base_image_digest=$(docker buildx imagetools inspect "${base_image}" --raw | jq -r '.config.digest')
+    # layers=$(docker buildx imagetools inspect "${base_image}" --format '{{json .}}' | jq '.image.rootfs.diff_ids')
+    last_layer=$(docker buildx imagetools inspect "${base_image}" --format '{{json .}}' | jq -r '.image.rootfs.diff_ids[-1]')
   fi
 
-
-
-  echo "Base image digest: $base_image_digest"
+  echo "$last_layer"
 }
 
-echo
-echo
-echo "Image: $image"
-get_top_base_layer
-exit 0
+top_base_layer=$(get_top_base_layer)
 
 # We blindly retry on failures, as we've seen unexplained failures in the scans that we couldn't resolve.
+success=0
 for i in {1..10}; do
   set +e
+  # Run a full scan, including the base image
   bash <(curl -s https://detect.blackduck.com/detect10.sh) \
     --blackduck.url=https://digitalasset.blackducksoftware.com/ \
     --blackduck.api.token="$BLACKDUCK_HUBDETECT_TOKEN" \
     --detect.docker.image="$image" \
     --detect.tools=DOCKER,SIGNATURE_SCAN \
     --detect.tools.excluded=BINARY_SCAN \
-    --detect.project.name=DACH-NY_canton-network-internal_images \
-    --detect.project.version.name="$image" \
+    --detect.project.name="DACH-NY_canton-network-internal_images-${image_name}" \
+    --detect.project.version.name="${image_version}-full" \
     --detect.docker.passthrough.imageinspector.service.port.alpine=$((BASE_PORT + (index*3) + 0)) \
     --detect.docker.passthrough.imageinspector.service.port.centos=$((BASE_PORT + (index*3) + 1)) \
     --detect.docker.passthrough.imageinspector.service.port.ubuntu=$((BASE_PORT + (index*3) + 2)) \
@@ -72,13 +75,50 @@ for i in {1..10}; do
 
   if [ $res -eq 0 ]; then
     echo "Black Duck scan completed successfully for image: $image"
-    exit 0
+    success=1
+    break
   else
     echo "Black Duck scan failed (attempt $i), retrying in 10 seconds..."
     sleep 10
   fi
 done
-echo "Black Duck scan failed after 10 attempts for image: $image"
-exit 1
+if [ $success -eq 0 ]; then
+  echo "Black Duck scan failed after 10 attempts for image: $image"
+  exit 1
+fi
 
-#TODO(DACH-NY/canton-network-internal#726): run also with `--detect.docker.platform.top.layer.id=sha256:...`, to detect separately vulnerabilities added by us on top of the base image
+# FIXME: refactor to reduce the duplication here
+success=0
+for i in {1..10}; do
+  set +e
+  # Run a scan only on the layers added by us, excluding the base image
+  bash <(curl -s https://detect.blackduck.com/detect10.sh) \
+    --blackduck.url=https://digitalasset.blackducksoftware.com/ \
+    --blackduck.api.token="$BLACKDUCK_HUBDETECT_TOKEN" \
+    --detect.docker.image="$image" \
+    --detect.tools=DOCKER,SIGNATURE_SCAN \
+    --detect.tools.excluded=BINARY_SCAN \
+    --detect.project.name="DACH-NY_canton-network-internal_images-${image_name}" \
+    --detect.project.version.name="$image_version" \
+    --detect.docker.passthrough.imageinspector.service.port.alpine=$((BASE_PORT + (index*3) + 0)) \
+    --detect.docker.passthrough.imageinspector.service.port.centos=$((BASE_PORT + (index*3) + 1)) \
+    --detect.docker.passthrough.imageinspector.service.port.ubuntu=$((BASE_PORT + (index*3) + 2)) \
+    --detect.output.path="${TMP_DIR}/output" \
+    --detect.tools.output.path="${TMP_DIR}/tool_output" \
+    --detect.docker.platform.top.layer.id="$top_base_layer" \
+  res=$?
+  set -e
+
+  if [ "$res" -eq 0 ]; then
+    echo "Black Duck scan completed successfully for image: $image"
+    success=1
+    break
+  else
+    echo "Black Duck scan failed (attempt $i), retrying in 10 seconds..."
+    sleep 10
+  fi
+done
+if [ $success -eq 0 ]; then
+  echo "Black Duck scan failed after 10 attempts for image: $image"
+  exit 1
+fi
