[skip ci] Revert "Add pulumi self hosted runner (#15103)" (#15218)
This reverts commit dfab99ed553b9429326c5cbb98bc7a2aa4b8fc7e.

diff --git a/.circleci/config/commands/commands.yml b/.circleci/config/commands/commands.yml
--- a/.circleci/config/commands/commands.yml
+++ b/.circleci/config/commands/commands.yml
@@ -178,6 +178,227 @@ commands:
           cmd_retry_condition: << parameters.cmd_retry_condition >>
           cmd_before_retry: << parameters.cmd_before_retry >>
 
+  run_bash_command_in_nix:
+    parameters:
+      cmd:
+        type: string
+      cmd_name:
+        type: string
+        default: Executing bash command << parameters.cmd >> in the nix shell
+      cmd_retry_count:
+        description: Number of times to retry the command
+        type: integer
+        default: 0
+      cmd_retry_wait:
+        description: Number of seconds to wait between retries
+        type: integer
+        default: 5
+      cmd_retry_condition:
+        description: Condition for retrying the command (up to the maximum number of retries)
+        type: string
+        default: "true"
+      cmd_before_retry:
+        description: Extra command to run before retrying the command
+        type: string
+        default: ""
+      gce_authenticate:
+        type: boolean
+        default: false
+      <<: *cluster-parameter
+      additional_nix_args:
+        type: string
+        default: ""
+      no_output_timeout:
+        type: string
+        default: "10m"
+      when:
+        type: enum
+        enum: ["on_success", "always", "on_fail"]
+        default: "on_success"
+      background:
+        type: boolean
+        default: false
+      working_dir:
+        type: string
+        default: ""
+    steps:
+      - get_cluster:
+          cluster: << parameters.cluster >>
+          when: << parameters.when >>
+      - run:
+          name: << parameters.cmd_name >>
+          when: << parameters.when >>
+          no_output_timeout: << parameters.no_output_timeout >>
+          background: << parameters.background >>
+          command: |
+            set -euo pipefail
+            . /home/circleci/.nix-profile/etc/profile.d/nix.sh
+            ADDITIONAL_NIX_ARGS="<< parameters.additional_nix_args >>"
+
+            if [ -n "<< parameters.working_dir >>" ]; then
+              echo "Changing into working directory << parameters.working_dir >>"
+              cd "<< parameters.working_dir >>"
+            fi
+
+            # Attempt to build the nix env with retries to work around transient download failures
+            MAX_RETRY_NIX_ENV=5
+            NIX_ENV_TRY_COUNT=0
+            until [ $NIX_ENV_TRY_COUNT -ge $MAX_RETRY_NIX_ENV ]
+            do
+              if [ $NIX_ENV_TRY_COUNT -gt 0 ]; then
+                SLEEP_DURATION=$((NIX_ENV_TRY_COUNT*2))
+                echo "Failed to build and enter the nix environment, retrying in $SLEEP_DURATION seconds..."
+                sleep $SLEEP_DURATION
+              fi
+              nix develop \
+                path:nix \
+                --ignore-environment \
+                --keep USER \
+                --keep HOME \
+                --keep TERM \
+                --keep CI \
+                --keep RUN_SPLITTED_TESTS_CMD \
+                --command echo "Confirmed that we can build and enter the nix environment!" \
+                && break
+              NIX_ENV_TRY_COUNT=$((NIX_ENV_TRY_COUNT+1))
+            done
+
+            if [ $NIX_ENV_TRY_COUNT -ge $MAX_RETRY_NIX_ENV ]; then
+              echo "Failed to build and enter the nix environment after $MAX_RETRY_NIX_ENV attempts"
+              exit 1
+            fi
+
+            # Run the command for real within the nix environment
+            nix develop \
+              path:nix \
+              --ignore-environment \
+              --keep USER \
+              --keep HOME \
+              --keep TERM \
+              --keep CI \
+              --keep RUN_SPLITTED_TESTS_CMD \
+              --keep GCP_DA_CN_DEVNET_KEY \
+              --keep GCP_DA_CN_CI_KEY \
+              --keep GCP_DA_CN_CI_2_KEY \
+              --keep GCP_DA_CN_SCRATCHNET_KEY \
+              --keep GCP_DA_CN_SCRATCHNET2_KEY \
+              --keep GCP_DA_CN_MAINNET_KEY \
+              --keep CIRCLE_BRANCH \
+              --keep TARGET_CLUSTER \
+              $ADDITIONAL_NIX_ARGS \
+              --command bash \<<'EOF'
+
+              set -euo pipefail
+
+              . .envrc.vars
+              if [[ "$TARGET_CLUSTER" != none ]]; then
+                . $REPO_ROOT/cluster/deployment/$TARGET_CLUSTER/.envrc.vars
+                . $REPO_ROOT/build-tools/lib/cluster.envrc.vars
+                echo "Using cluster hostname suffix: ${GCP_CLUSTER_HOSTNAME}"
+              fi
+
+              if [[ << parameters.gce_authenticate >> == true ]]; then
+                if [[ "$TARGET_CLUSTER" == none ]]; then
+                  echo "TARGET_CLUSTER must be set"
+                  exit 1
+                fi
+                # Authenticate to the correct GCP project for the cluster
+                echo "Authenticating to cluster \"$TARGET_CLUSTER\" in project \"${CLOUDSDK_CORE_PROJECT}\""
+                case ${CLOUDSDK_CORE_PROJECT} in
+                  da-cn-scratchnet)
+                    export CN_ACTIVE_ENVIRONMENT_KEY="${GCP_DA_CN_SCRATCHNET_KEY}"
+                    ;;
+
+                  da-cn-scratchnet2)
+                    export CN_ACTIVE_ENVIRONMENT_KEY="${GCP_DA_CN_SCRATCHNET2_KEY}"
+                    ;;
+
+                  da-cn-ci)
+                    export CN_ACTIVE_ENVIRONMENT_KEY="${GCP_DA_CN_CI_KEY}"
+                    ;;
+
+                  da-cn-ci-2)
+                    export CN_ACTIVE_ENVIRONMENT_KEY="${GCP_DA_CN_CI_2_KEY}"
+                    ;;
+
+                  da-cn-devnet)
+                    export CN_ACTIVE_ENVIRONMENT_KEY="${GCP_DA_CN_DEVNET_KEY}"
+                    ;;
+
+                  da-cn-mainnet)
+                    export CN_ACTIVE_ENVIRONMENT_KEY="${GCP_DA_CN_MAINNET_KEY}"
+                    ;;
+
+                  *)
+                    echo "Cannot authenticate to GCP project without key: ${CLOUDSDK_CORE_PROJECT}"
+                    exit 1
+                    ;;
+                esac
+
+                # GOOGLE_CREDENTIALS variable is used by pulumi
+                export GOOGLE_CREDENTIALS=${CN_ACTIVE_ENVIRONMENT_KEY}
+
+                # TODO(#7702) Extract retry logic for CI tasks into command/script
+                # gcloud auth with a limited number of retries
+                MAX_AUTH_RETRIES=5
+                AUTH_TRY_COUNT=0
+                AUTH_RETRY_WAIT=30
+                until [ $AUTH_TRY_COUNT -gt $MAX_AUTH_RETRIES ]
+                do
+                    echo "Trying gcloud auth. Attempt #$[AUTH_TRY_COUNT+1]"
+
+                    # Try to authenticate and break retry loop in case of success
+                    echo ${CN_ACTIVE_ENVIRONMENT_KEY} | gcloud auth activate-service-account --key-file=- && break
+
+                    AUTH_TRY_COUNT=$[$AUTH_TRY_COUNT+1]
+                    sleep $AUTH_RETRY_WAIT
+                done
+
+                if [ $AUTH_TRY_COUNT -gt $MAX_AUTH_RETRIES ]; then
+                    echo "Exceeded maximum retries ($AUTH_TRY_COUNT / $MAX_AUTH_RETRIES), no more attempts: gcloud auth activate-service-account" >&2
+                    exit 1
+                fi
+
+              fi
+
+              MAX_RETRY=<< parameters.cmd_retry_count >>
+              n=0
+              until [ $n -gt $MAX_RETRY ]
+              do
+                  if [ $n -gt 0 ]; then
+                    sleep << parameters.cmd_retry_wait >>
+                    << parameters.cmd_before_retry >>
+                  fi
+                  cmd_wrapper() {
+                    # We write the cmd to a separate file. That way `set -e` statements in the cmd will take effect
+                    # despite us using this in a tested context below where they would usually be disabled.
+                    # See https://gist.github.com/cocreature/9c345b75b7dad05ed32865b21c1b0460 for a minimal example
+                    # of what happens if we just call parameters.cmd directly.
+                    # We enforce set -euo pipefail by including it in all the commands. Even if the command has already set it, then it will have no effect
+                    # but this way we ensure all the commands will fail on error and no lead to confusing behaviour
+                    # append random string to the cmd.sh file to avoid parallel steps writing and executing the same cmd.sh files
+                    CMD_FILE=$(mktemp cmd-XXXXXX.sh)
+                    cat \<<'EOF2' > $CMD_FILE
+                    set -euo pipefail
+                    echo "Running command"
+                    << parameters.cmd >>
+            EOF2
+                    bash $CMD_FILE
+                  }
+                  cmd_wrapper && break
+                  if [ << parameters.cmd_retry_condition >> != true ]; then
+                    echo "Retry condition not met, not retrying" >&2
+                    exit 1
+                  fi
+                  n=$[$n+1]
+              done
+
+              if [ $n -gt $MAX_RETRY ]; then
+                echo "Exceeded maximum retries ($n / $MAX_RETRY), no more attempts << parameters.cmd_name >>" >&2
+                exit 1
+              fi
+            EOF
+
   cleanup_sbt_test_job:
     parameters:
       upload_caches:
@@ -642,6 +863,10 @@ commands:
               echo "export TARGET_CLUSTER=<< parameters.cluster >>" >> "$BASH_ENV"
             fi
           when: << parameters.when >>
+      - run:
+          name: Print TARGET_CLUSTER for debugging
+          command: echo "TARGET_CLUSTER set to $TARGET_CLUSTER"
+          when: << parameters.when >>
 
   preview_pulumi:
     parameters:
@@ -701,6 +926,9 @@ commands:
             TARGET_BRANCH=$(curl -s -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/DACH-NY/canton-network-node/pulls/$PR_NUMBER | jq -r '.base.ref')
             echo "PR target branch: $TARGET_BRANCH"
             echo export "TARGET_BRANCH=\"$TARGET_BRANCH\"" >> "$BASH_ENV"
+      - run:
+          name: Print TARGET_BRANCH for debugging
+          command: echo "TARGET_BRANCH set to $TARGET_BRANCH"
 
   clone_and_update_oss_or_splice:
       parameters:
