Check for empty VPN_IP, print to check VPN, exit. (#3813)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -642,6 +642,7 @@ commands:
             # Virtual IP setup by charon-cmd, we assume this is only ip4 interface without a broadcast address.
             echo "Querying for VPN IP"
             VPN_IP=$(sudo ip --json addr show dev ens5 | tee /dev/stderr | jq -r '.[0].addr_info | .[] | select(.family == "inet" and (has("broadcast") | not)) | .local')
+            [[ -z "$VPN_IP" ]] && { echo "Cannot find VPN_IP, please check VPN connectivity" ; exit 1; }
             echo "Querying for network gateway"
             GATEWAY=$(sudo ip --json route list | tee /dev/stderr | jq -r '.[]|select(.gateway)|.gateway')
             echo "Querying for egress IP"
