Unify the tags used for docker and helm charts (#5138)

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -813,14 +813,20 @@ commands:
                exit 1
            fi
 
-           if [ ${cluster_version:0:4} != "git-" ]; then
+
+           if [[ ${cluster_version:0:4} == "git-" ]]; then
+              # Deprecated cluster version format
+              cluster_git_commit="${cluster_version:4}"
+           elif [[ ${cluster_version} =~ ^[0-9.]*-snapshot[0-9.]*v[0-9a-z]* ]]; then
+              cluster_git_commit="$(echo "${cluster_version}" | sed 's/.*v//')"
+           else
               echo "Unexpected cluster version format: ${cluster_version}."
               exit 2
            fi
 
-           echo "Checking out: ${cluster_version:4}"
-           if ! git checkout ${cluster_version:4}; then
-              echo "Cannot checkout cluster version: ${cluster_version:4}."
+           echo "Checking out: ${cluster_git_commit}"
+           if ! git checkout ${cluster_git_commit}; then
+              echo "Cannot checkout cluster version: ${cluster_git_commit}."
               exit 3
            fi
 
@@ -1085,7 +1091,7 @@ jobs:
          cmd: |
            echo $GCP_DA_CN_IMAGES_KEY | gcloud auth activate-service-account --key-file=-
            export GOOGLE_CLOUD_PROJECT=da-cn-images
-           VERSION=$(version-gen)
+           VERSION=$(get-snapshot-version)
            (cd /tmp/artifacts ; for filename in *.tar.gz; do mv "$filename" "${VERSION}_${filename}"; done)
            # we cp with -n so that it doesn't try to overwrite an already uploaded bundle with this version,
            # which would lead to an error due to a misisng `delete` permission
