[static] upload bundles as part of artifacts_push

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -3378,29 +3378,6 @@ jobs:
       - execute_sbt_command:
           # compile tests, as well as bundle, to make sure the cache that is uploaded here is complete
           cmd: "Test/compile bundle"
-      - run:
-          name: Copy bundle
-          command: |
-            set -eou pipefail
-            mkdir -p /tmp/artifacts
-            cp apps/app/target/release/*.tar.gz /tmp/artifacts
-      - run_bash_command_in_nix:
-          cmd_name: Copy OpenAPI specs
-          cmd: |
-            set -eou pipefail
-            scripts/copy-openapi.sh /tmp/artifacts/openapi.tar.gz
-      - run_bash_command_in_nix:
-          cmd_name: Publish release bundles
-          additional_nix_args: "--keep GCP_DA_CN_SHARED_KEY"
-          cmd: |
-            echo $GCP_DA_CN_SHARED_KEY | gcloud auth activate-service-account --key-file=-
-            export GOOGLE_CLOUD_PROJECT=da-cn-shared
-            VERSION=$(get-snapshot-version)
-            (cd /tmp/artifacts ; for filename in *.tar.gz; do mv "$filename" "${VERSION}_${filename}"; done)
-            # we cp with -n so that it doesn't try to overwrite an already uploaded bundle with this version,
-            # which would lead to an error due to a misisng `delete` permission
-            gsutil cp -n /tmp/artifacts/*.tar.gz gs://cn-release-bundles
-          # we're not adding a cmd_retry_count here because of the `mv` above and because gsutil cp has a retry mechanism of its own
       - save_sbt_job_result:
           runner_type: "selfhosted"
           upload_caches: true
@@ -3543,6 +3520,29 @@ jobs:
             make cluster/helm/build -j
             make cluster/helm/push -j
           cmd_retry_count: 5
+      - run:
+          name: Copy bundle
+          command: |
+            set -eou pipefail
+            mkdir -p /tmp/artifacts
+            cp apps/app/target/release/*.tar.gz /tmp/artifacts
+      - run_bash_command_in_nix:
+          cmd_name: Copy OpenAPI specs
+          cmd: |
+            set -eou pipefail
+            scripts/copy-openapi.sh /tmp/artifacts/openapi.tar.gz
+      - run_bash_command_in_nix:
+          cmd_name: Publish release bundles
+          additional_nix_args: "--keep GCP_DA_CN_SHARED_KEY"
+          cmd: |
+            echo $GCP_DA_CN_SHARED_KEY | gcloud auth activate-service-account --key-file=-
+            export GOOGLE_CLOUD_PROJECT=da-cn-shared
+            VERSION=$(get-snapshot-version)
+            (cd /tmp/artifacts ; for filename in *.tar.gz; do mv "$filename" "${VERSION}_${filename}"; done)
+            # we cp with -n so that it doesn't try to overwrite an already uploaded bundle with this version,
+            # which would lead to an error due to a misisng `delete` permission
+            gsutil cp -n /tmp/artifacts/*.tar.gz gs://cn-release-bundles
+          # we're not adding a cmd_retry_count here because of the `mv` above and because gsutil cp has a retry mechanism of its own
       - run_bash_command_in_nix:
           cmd_name: tag git
           additional_nix_args: "--keep ARTIFACTORY_USER \
